name: call-bx3

on:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/bx3.yml
    with:
      issue_number: 1
      issue_body: "bisect"
      project_name: kaji-wbs
    secrets: inherit
